#!/usr/bin/env ruby

require 'drb'

class Controller
  def send_command command
    system("qdbus org.kde.amarok /Player org.freedesktop.MediaPlayer.#{command} > /dev/null")
  end
end

DRb.start_service "druby://:42423", Controller.new
DRb.thread.join
